nanudaDev/nanuda-b2b-platform-api

- TODO.md
- src/app.module.ts
- src/core/utils/nanuda-slack-notification.service.ts
- src/core/utils/new-data-duplicate-key-remover.util.ts
- src/main.ts
- src/modules/auth/auth.service.ts
- src/modules/company-district/company-district-analysis-sender.service.ts
- src/modules/company-district/company-district.service.ts
- src/modules/dashboard/admin-dashboard.controller.ts
- src/modules/delivery-founder-consult-contract/delivery-founder-consult-contract.service.ts
- src/modules/delivery-founder-consult/delivery-founder-consult.service.ts
- src/modules/favorite-space-mapper/favorite-space-mapper.entity.ts
- src/modules/file-upload/file-upload.service.ts
- src/modules/founder-consult/founder-consult.service.ts
- src/modules/sms-auth/sms-auth.service.ts
major refactoring + delivery founder consult innerjoin to left join
b61d9ba
@joseph-nanuda
Merge pull request #23 from nanudaDev/platform-joseph …
7a0487b
@joseph-nanuda
Update favorite-space-mapper.entity.ts
c6f11ff
@joseph-nanuda
Merge pull request #24 from nanudaDev/platform-joseph
> major refactoring

- src/modules/delivery-founder-consult/delivery-founder-consult.service.ts
- src/modules/notice-board/dto/admin-notice-board-create.dto.ts
- src/modules/notice-board/dto/admin-notice-board-update.dto.ts
- src/modules/notice-board/notice-board.entity.ts
- src/modules/notice-board/notice-board.service.ts
tempSaveYn으로 임시 저장한다.
업체 사용자들은 .where('tempSaveYn = :tempSaveYn', {tempSaveYn: YN.NO})
기준으로 SELECT한다
> 공지사항 임지 저장 기능

- src/modules/company-district/dto/admin-company-district-update.dto.ts
- src/modules/company-district/dto/index.ts
업체 지점에서 업체 정보 수정
6127b3d
@joseph-nanuda
Merge branch 'staging' of https://github.com/nanudaDev/nanuda-b2b-pla… …
e7e7c31
@joseph-nanuda
Updated district dto index
> 업체 지점에서 업체 정보 수정

- src/modules/delivery-founder-consult-contract/admin-delivery-founder-consult-contract.controller.ts
- src/modules/delivery-founder-consult-contract/delivery-founder-consult-contract.controller.ts
- src/modules/delivery-founder-consult-contract/delivery-founder-consult-contract.service.ts
- src/modules/delivery-founder-consult-contract/dto/admin-delivery-founder-consult-contract-list.dto.ts
delivery founder consult contract에 다음 dto추가:
@ApiPropertyOptional()
@IsOptional()
@Expose()
companyNameKr?: string;
@ApiPropertyOptional()
@IsOptional()
@Expose()
companyNameEng?: string;
> admin delivery founder consult refactoring

- src/modules/delivery-space/admin-delivery-space.controller.ts
- src/modules/delivery-space/delivery-space.service.ts
ex)
'/admin/company-district/delivery-space/:id([0-9]+)/next'
'/admin/delivery-space/:id([0-9]+)/next'
> added find next with district and with without

- src/app.module.ts
- src/modules/dashboard/dashboard.module.ts
- src/modules/dashboard/payment-list.entity.ts
- src/modules/delivery-space/admin-delivery-space.controller.ts
> added payment list from kitchen DB

- src/modules/inquiry/admin-inquiry.controller.ts
- src/modules/inquiry/inquiry.service.ts
> close inquiry for admin

- src/modules/notice-board/dto/admin-notice-board-create.dto.ts
- src/modules/notice-board/dto/admin-notice-board-update.dto.ts
- src/modules/notice-board/notice-board.service.ts
> notice board attachments update

- src/modules/notice-board/dto/admin-notice-board-create.dto.ts
- src/modules/notice-board/dto/admin-notice-board-update.dto.ts
- src/modules/notice-board/notice-board.service.ts
@joseph-nanuda
notice board attachments update
> notice board attachments update 

- src/modules/sms-auth/sms-auth.service.ts
>  인증번호 기본값 설정하기

- src/modules/company-district/company-district.service.ts
> delivery space length for admin

- src/modules/company-district/company-disctrict.module.ts
- src/modules/company-district/nanuda-company-district.controller.ts
- src/modules/company-district/nanuda-company-district.service.ts
> 캐이스 1 지점 검색 필드 라우트 추가

- src/modules/delivery-space/delivery-space.entity.ts
- src/modules/delivery-space/nanuda-delivery-space.service.ts
> consult count for nanuda user

- src/modules/company-district/admin-company-district.controller.ts
- src/modules/company-district/company-district.entity.ts
- src/modules/company-district/company-district.service.ts
- src/modules/delivery-space/nanuda-delivery-space.service.ts
@joseph-nanuda
찜 공간 likedYn false
> 찜 공간 likedYn false

- src/modules/company-district/nanuda-company-district.service.ts
- src/modules/payment-list/admin-payment-list.controller.ts
- src/modules/payment-list/dto/admin-payment-list.dto.ts
- src/modules/payment-list/payment-list.entity.ts
- src/modules/payment-list/payment-list.service.ts
@joseph-nanuda
filter delivery space results for nanuda homepage
@joseph-nanuda
payment list entity 리팩토링
> payment list entity 리팩토링

- src/modules/company-district/nanuda-company-district.service.ts
@joseph-nanuda
dropdown refactoring
> Platform joseph

- src/app.module.ts
- src/modules/answer/answer.entity.ts
- src/modules/article/article.service.ts
- src/modules/article/dto/admin-article-update.dto.ts
- src/modules/article/nanuda-article.service.ts
- src/modules/company-district/nanuda-company-district.controller.ts
- src/modules/company-district/nanuda-company-district.service.ts
- src/modules/delivery-space/nanuda-delivery-space.controller.ts
- src/modules/delivery-space/nanuda-delivery-space.service.ts
- src/modules/index.ts
- src/modules/question/dto/admin-question-create.dto.ts
- src/modules/question/nanuda-question.controller.ts
- src/modules/question/nanuda-question.service.ts
- src/modules/question/question.entity.ts
- src/modules/question/question.module.ts
- src/modules/question/question.service.ts
- src/modules/survey/nanuda-survey.controller.ts
- src/modules/survey/nanuda-survey.service.ts
- src/modules/survey/survey.entity.ts
- src/modules/survey/survey.module.ts
@joseph-nanuda
기사 업데이트 버그 수정
2f15587
@joseph-nanuda
질문 관련 API 작업 1차
23fdccb
Commits on Sep 20, 2020
@bbogeul
Merge branch 'staging' into platform-joseph
365d27e
Commits on Sep 21, 2020
@joseph-nanuda
기사 업데이트 DTO애 showYn 추가하기
>  기사 업데이트 DTO애 showYn 추가하기

- src/app.module.ts
- src/modules/answer/answer.entity.ts
- src/modules/best-space/best-space.entity.ts
- src/modules/best-space/best-space.module.ts
- src/modules/best-space/best-space.service.ts
- src/modules/best-space/dto/admin-best-space-list.dto.ts
- src/modules/best-space/dto/index.ts
- src/modules/best-space/dto/nanuda-best-space-list.dto.ts
- src/modules/best-space/nanuda-best-space.controller.ts
- src/modules/best-space/nanuda-best-space.service.ts
- src/modules/delivery-space/delivery-space.entity.ts
- src/modules/delivery-space/delivery-space.service.ts
- src/modules/delivery-space/dto/admin-delivery-space-create.dto.ts
- src/modules/delivery-space/dto/admin-delivery-space-update.dto.ts
- src/modules/delivery-space/dto/delivery-space-create.dto.ts
- src/modules/delivery-space/dto/delivery-space-list.dto.ts
- src/modules/delivery-space/dto/delivery-space-update.dto.ts
- src/modules/delivery-space/nanuda-delivery-space.controller.ts
- src/modules/delivery-space/nanuda-delivery-space.service.ts
- src/modules/index.ts
- src/modules/question/nanuda-question.service.ts
- src/modules/question/question.entity.ts
- src/modules/survey/nanuda-survey.controller.ts
- src/modules/survey/nanuda-survey.service.ts
- src/modules/survey/survey.entity.ts
> 배달형 공간 모듈 리팩토링 및 베스트 공간 개발

- src/modules/delivery-space/delivery-space.service.ts
- src/modules/delivery-space/dto/admin-delivery-space-update.dto.ts
- src/modules/delivery-space/nanuda-delivery-space.service.ts
- src/modules/homepage/nanuda-homepage.controller.ts
- src/modules/homepage/nanuda-homepage.service.ts
> best delivery space and best restaurant kitchen spaces

- src/core/utils/b2c-nanuda-slack-notification.service.ts
- src/core/utils/index.ts
- src/core/utils/nanuda-sms-notification.service.ts
- src/core/utils/sms-notification.service.ts
- src/modules/attendees/attendees.entity.ts
- src/modules/attendees/attendees.module.ts
- src/modules/attendees/attendees.service.ts
- src/modules/attendees/dto/admin-attendees-create.dto.ts
- src/modules/attendees/dto/admin-attendees-update.dto.ts
- src/modules/attendees/dto/index.ts
- src/modules/attendees/dto/nanuda-attendees-create.dto.ts
- src/modules/attendees/nanuda-attendees.controller.ts
- src/modules/attendees/nanuda-attendees.service.ts
- src/modules/brand/brand.entity.ts
- src/modules/presentation-event/admin-presentation-event.controller.ts
- src/modules/presentation-event/dto/admin-presentation-event-create.dto.ts
- src/modules/presentation-event/dto/admin-presentation-event-update.dto.ts
- src/modules/presentation-event/nanuda-presentation-event.controller.ts
- src/modules/presentation-event/nanuda-presentation-event.service.ts
- src/modules/presentation-event/presentation-event.entity.ts
- src/modules/presentation-event/presentation-event.module.ts
- src/modules/presentation-event/presentation-event.service.ts
- src/modules/sms-auth/sms-auth.module.ts
- src/modules/space-type/space-type.entity.ts
1. 창업 설명회 기눙 (CRUD)
2. 참석자 모집 기능 (CRUD)
3. 기존 서버 문자 및 슬랙 노티 부분 이동 완료
> presentation event and attendees modules

- src/modules/presentation-event/admin-presentation-event.controller.ts
- src/modules/presentation-event/dto/admin-presentation-event-update.dto.ts
- src/modules/presentation-event/presentation-event.entity.ts
- src/modules/presentation-event/presentation-event.service.ts
posteventDesc => postEventDesc
> added hard delete for presentation event

- src/modules/company-district-promotion/nanuda-company-district-promotion.service.ts
- src/modules/delivery-space/nanuda-delivery-space.controller.ts
- src/modules/delivery-space/nanuda-delivery-space.service.ts
- src/modules/homepage/nanuda-homepage.service.ts
1. nanuda-api: NP-1234_joseph브랜치에서 풀 받으시면 되고 엔드포인트는 /deliverySpace/maxValues
> inner join and select for company

- src/app.module.ts
- src/core/typeorm/select-query-builder.declaration.ts
- src/core/utils/nanuda-sms-notification.service.ts
- src/modules/best-space/best-space.service.ts
- src/modules/company-district/admin-company-district.controller.ts
- src/modules/company-district/company-district.service.ts
- src/modules/company/admin-company.controller.ts
- src/modules/company/company.service.ts
- src/modules/delivery-founder-consult-record/admin-delivery-founder-consult-record.controller.ts
- src/modules/delivery-founder-consult-record/delivery-founder-consult-record.entity.ts
- src/modules/delivery-founder-consult-record/delivery-founder-consult-record.module.ts
- src/modules/delivery-founder-consult-record/delivery-founder-consult-record.service.ts
- src/modules/delivery-founder-consult/admin-delivery-founder-consult.controller.ts
- src/modules/delivery-founder-consult/delivery-founder-consult.service.ts
- src/modules/delivery-founder-consult/dto/admin-delivery-founder-consult-update.dto.ts
- src/modules/delivery-space/admin-delivery-space.controller.ts
- src/modules/delivery-space/delivery-space.service.ts
- src/modules/index.ts
- src/modules/message-delivery-space/admin-message-delivery-space.service.ts
1. 배달형 공간 변경 이력 및 변경 기능 추가
2. 불필요한 로직 제거
3. 허용 가능한 업체, 지점, 및 타입 엔드포인트 추가 
4. 모든 업체, 지점, 타입 배열로 받는 엔드포인트 추가 
5. CustomInnerJoin 및 CustomLeftJoin select query builder에 추가
> refactoring

- src/modules/company-district/admin-company-district.controller.ts
- src/modules/company-district/company-district.service.ts
> find for analysis select

- src/core/utils/nanuda-sms-notification.service.ts
- src/core/utils/sms-notification.service.ts
- src/modules/company-district/company-district.service.ts
- src/modules/delivery-founder-consult/nanuda-delivery-founder-consult.service.ts
- src/modules/delivery-space/dto/delivery-space-list.dto.ts
- src/modules/delivery-space/nanuda-delivery-space.service.ts
> 장바구니 형식 문자 발송 기능

- src/modules/delivery-space/dto/admin-delivery-space-list.dto.ts
> added isOperatedYn
